name:                hexml-lens-lite
version:             0.1.0.0
license:             AllRightsReserved
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "(c) 2020, DeepFlow, Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Some great library and/or tool made by DeepFlow, Inc.

language:           GHC2021

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- hexml
- bytestring
- lens

library:
  source-dirs: src
